### PR TITLE
Modified MessageFeedServlet to print users' messages in JSON format

### PR DESCRIPTION
**Pull request by archthegit**
Modified MessageFeedServlet class's get function to show users' posted messages in json format

### CODE REVIEW

**Comment by SuyashLakhotia** [comment]
Hey @archthegit, thanks for the early PR! Do you think you could check your editor's formatting settings? I have a feeling your indentation is set to 4 spaces instead of 2 (take a look at the diff for `Message.java`).

**Comment by archthegit** [comment]
@SuyashLakhotia I fixed the settings on intelliJ and autformated the classes. But what is stickler-ci? And why does it say I am missing a stickler.yaml?

**Comment by SuyashLakhotia** [comment]
@archthegit Ah. Its this new tool I integrated to check formatting errors automatically! Posted about it in our team chat. Just merge from master -> your_branch and it should be fine! :)

**Comment by SuyashLakhotia** [comment]
Just merge from master -> your_branch once and have the checks pass. I can merge it after. :)

**Comment by archthegit** [comment]
@SuyashLakhotia cool, done!

**Pull request merged**
