### PR TITLE
Add star rating in Book List

### PR DESCRIPTION
**Pull request by karenfrilya97**

### CODE REVIEW

**Comment by SuyashLakhotia** [comment]
Are there eventually plans to simply put blank stars + filled in stars to accurately represent the rating? This is just 0, 5 or 10 stars right?

**Comment by karenfrilya97** [comment]
No, star-0 is blank star (0/10), star-5 is half filled star. (5/10), star-10 is filled in star (10/10). So, the star rating shown is rounded down to 0, 0.5, 1, 1.5, etc.

**Comment by jannatbedi** [comment]
Oh got it! But  a user will not be able to provide an x.5 rating right?? The user can provide the rating as an integer only, whereas the average can be float

**Comment by karenfrilya97** [comment]
I think so. But I'm not sure if we implemented adding review yet.

**Pull request merged**
